# Generated by Django 3.0.8 on 2020-09-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btpsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
    ]
