# Generated by Django 3.0.8 on 2020-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btpsite', '0002_auto_20200915_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
