# Generated by Django 3.0.8 on 2020-09-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btpsite', '0003_auto_20200915_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='image_link',
            field=models.ImageField(blank=True, upload_to='btpsite_image'),
        ),
    ]
