# Generated by Django 3.0.8 on 2020-09-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btpsite', '0004_auto_20200916_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('AUTRE', 'AUTRE')], max_length=25),
        ),
    ]
